import jwt from "jsonwebtoken"
import { Token } from "~/types/core"
import { AUTHENTICATION_TOKEN_EXPIRATION_HOURS } from "~/server/constants"

// Generate a random 8-digit number as the email token
export const generateEmailToken = (): string => Math.floor(Math.random() * 100000000).toString()

// Generate a signed JWT token with the tokenId in the payload
export const generateToken = (token: Token): string => {
  return jwt.sign(
    {
      tokenId: token.id,
      iat: token.createdAt.getTime() / 1000, // now
      exp: token.createdAt.getTime() / 1000 + AUTHENTICATION_TOKEN_EXPIRATION_HOURS * 60 * 60, // 12 hours from now
    },
    process.env.JWT_SECRET!,
    {},
  )
}
// Note: The environment variable JWT_SECRET can be generated by running the following command:
// $ node -e "console.log(require('crypto').randomBytes(256).toString('base64'));"
// This should always be set in production environments.
